# Generated by Django 5.2 on 2025-05-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('rent', 'Rent'), ('travel', 'Travel'), ('others', 'Others'), ('salary', 'Salary'), ('Scholarship', 'scholarship')], max_length=100),
        ),
    ]
